// src/components/Navbar.vue
<template>
  <nav class="navbar">
    <div class="container">
      <router-link to="/" class="navbar-item"> HOME </router-link>
      <router-link to="/contact" class="navbar-item"> CONTACT </router-link>
    </div>
  </nav>
</template>

<script>
export default {
  name: 'Navbar',
};
</script>

<style scoped>
.navbar {
  height: 60px;
  width: 100%;
  position: fixed;
  background: #ca3433;
  z-index: 1000;
}

.navbar-item {
  font-weight: 900;
  color: white;
  text-decoration: none;
}

.container {
  height: 100%;
  width: 70%;
  margin: auto;
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>

// components/navbar/Navbar.tsx
import Link from "next/link";
import { styled } from "../../stitches.config";

export const Navbar = () => {
  return (
    <s.Nav>
      <Link href="/" passHref={true}>
        <s.NavbarLink>Nikolaj Jensen</s.NavbarLink>
      </Link>

      <s.Links>
        <Link href="/works" passHref={true}>
          <s.NavbarLink>Works</s.NavbarLink>
        </Link>
        <Link href="/posts" passHref={true}>
          <s.NavbarLink>Posts</s.NavbarLink>
        </Link>
      </s.Links>
    </s.Nav>
  );
};

namespace s {
  export const Nav = styled("nav", {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "$2 $6",
    width: "90%",
    margin: "0 auto",

    "@md": {
      width: "740px",
    },
  });

  export const Links = styled("div", {
    display: "flex",
  });

  export const NavbarLink = styled("a", {
    position: "relative",
    display: "inline-block",
    verticalAlign: "top",
    paddingBottom: "$6",
    color: "$white",
    fontSize: "$xl",
    fontWeight: "bold",
    textTransform: "uppercase",
    textDecoration: "none",

    "& + &": { marginLeft: "$4" },

    "&:hover": {
      "&::before": {
        transform: "translateX(-50%)",
        borderRadius: "100%",
        position: "absolute",
        background: "$white",
        bottom: "10px",
        height: "8px",
        content: "",
        width: "8px",
        left: "50%",
      },
    },
  });
}
