// components/Navbar.vue
<template>
  <nav
    class="bg-white w-screen shadow sticky top-0 z-50 p-4"
  >
    <div class="flex flex-wrap items-center justify-between mx-auto max-w-6xl md:w-4/5">
      <h1 class="text-2xl font-bold text-gray-800">
        Nikolaj Jensen.
      </h1>

      <div class="flex md:hidden">
        <button @click="openCloseMenu">
          <img
            class="toggle block h-8"
            src="https://img.icons8.com/fluent-systems-regular/2x/menu-squared-2.png"
          >
          <img
            class="toggle hidden h-8"
            src="https://img.icons8.com/fluent-systems-regular/2x/close-window.png"
          >
        </button>
      </div>

      <div
        class="toggle hidden w-full flex flex-col items-center my-4 md:flex md:flex-row md:my-0 md:w-auto md:mt-0 md:space-x-4"
      >
        <NuxtLink to="/" class="block md:inline-block text-gray-900 hover:text-gray-500">
          Home
        </NuxtLink>

        <NuxtLink to="/cv" class="block md:inline-block text-gray-900 hover:text-gray-500">
          CV
        </NuxtLink>

        <NuxtLink to="/contact" class="block md:inline-block text-gray-900 hover:text-gray-500">
          Contact
        </NuxtLink>
      </div>
    </div>
  </nav>
</template>

<script>
export default {
  methods: {
    openCloseMenu () {
      const navToggle = document.getElementsByClassName('toggle')
      for (let i = 0; i < navToggle.length; i++) {
        navToggle.item(i).classList.toggle('hidden')
      }
    }
  }
}
</script>

// components/Navbar.tsx
import Link from 'next/link'
import { useTheme } from '../hooks/themeToggle';

interface Props {
  props?: any
}

const Navbar = ({ ...props }: Props) => {
  const [toggleTheme] = useTheme();

  return (
    <nav {...props} className="sticky top-0 left-0 w-screen h-12 bg-white z-50 shadow dark:text-white dark:bg-gray-900">
      <div className="flex h-12 max-w-xl mx-auto items-center justify-between">
        <Link href="/"><a className="text-2xl font-semibold tracking-wider">Nikolaj Jensen.</a></Link>

        <code className="cursor-pointer font-bold" onClick={toggleTheme}>Toggle</code>

        <div>
          <Link href="/works"><a className="text-xl font-semibold ml-2">Works</a></Link>
          <Link href="/posts"><a className="text-xl font-semibold ml-2">Posts</a></Link>
        </div>
      </div>
    </nav>
  )
}

export default Navbar
