// components/SkillPill.vue
<template>
  <span
    class="inline-flex items-center px-4 py-1 rounded-full font-medium leading-5 bg-gray-300 text-primary-600 mb-2 mr-2"
  >
    <img class="h-6 w-6 mr-1 -ml-2 rounded-full" :src="image">
    {{ text }}
  </span>
</template>

<script>
export default {
  props: {
    image: {
      type: String,
      required: true
    },
    text: {
      type: String,
      default: ''
    }
  }
}
</script>

// components/SkillPill.tsx
interface Props {
  title: string,
  icon: string,
}

const SkillPill = ({ title, icon }: Props) => {
  return (
    <div className="flex rounded-full items-center overflow-hidden bg-gray-200 h-10 mr-4 my-1">
      <img className="rounded-full h-10 w-10" src={icon} />
      <code className="mx-2 text-sm font-semibold">{title}</code>
    </div>
  )
}

export default SkillPill
