// src/components/Frontpage.vue
<template>
  <div className="frontpage">
    <h1 className="frontpage-title">
      Hey, I'm <strong className="text-danger">Nikolaj Jensen</strong>.
    </h1>
    <p className="frontpage-undertitle">
      Specialized <strong className="text-danger">biologist</strong> and
      experienced <strong className="text-danger">developer</strong>
    </p>
    <!-- <Button title="See my work" /> -->
  </div>
</template>

<script>
/* import Button from '@/components/Button.vue'; */

export default {
  name: 'Frontpage',
  components: {
    /* Button, */
  },
};
</script>

<style scoped>
.frontpage {
  height: 80vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
}

.frontpage-title {
  font-size: 3rem;
}

.frontpage-title > strong {
  color: #ca3433;
}

.frontpage-undertitle {
  font-size: 2rem;
  margin: 2rem;
  margin-bottom: 4rem;
}

.frontpage-undertitle > strong {
  color: #ca3433;
}
</style>

// src/pages/frontpage.jsx
import React, { Component } from "react";

const style = {
  height: "80vh",
  display: "flex",
  flexDirection: "column",
  justifyContent: "center",
  alignItems: "center",
};

export default class Frontpage extends Component {
  render() {
    return (
      <div className="p-5" style={style}>
        <div>
          <h1 className="display-4 text-center">
            Hey, I'm <strong className="text-danger">Nikolaj Jensen</strong>.
          </h1>
          <p className="h3 text-center">
            Specialized <strong className="text-danger">biologist</strong> and
            experienced <strong className="text-danger">developer</strong>
          </p>
          <p className="p-5 text-center">
            <button
              className="btn btn-outline-dark btn-lg"
              type="button"
              onClick={this.props.scrollFunction}
            >
              See my work
            </button>
          </p>
        </div>
      </div>
    );
  }
}
