// src/components/Projects.vue
<template>
  <div class="projects">
    <h1 id="projects-title">PROJECTS</h1>
    <div class="google-ios-button-row">
      <Button @click="newTab(googleLink)" title="Google Play" />
      <Button @click="newTab(appleLink)" title="Apple Store" />
    </div>

    <div class="cards">
      <Card
        image="/assets/flutter/reddit.png"
        label="FLUTTER APP"
        title="Speed (Reddit Client)"
      />
      <Card
        image="/assets/flutter/sygepleje.png"
        label="FLUTTER APP"
        title="Sygeplejersken"
      />
      <Card
        image="/assets/flutter/sialia.png"
        label="FLUTTER APP"
        title="Sialia for Twitter"
      />
      <Card
        image="/assets/flutter/walls.png"
        label="FLUTTER APP"
        title="Walls"
      />
      <Card
        image="/assets/flutter/physiology.png"
        label="FLUTTER APP"
        title="Physiology"
      />
      <Card
        image="/assets/flutter/pexels.png"
        label="FLUTTER APP"
        title="Pexels Wallpapers"
      />
      <Card
        image="/assets/react/sorting.png"
        link="http://nikolajjsj.github.io/Sorting-Visualization/"
        label="REACT - Web App"
        title="Sorting Visualizer"
      />
      <Card
        image="/assets/react/pathfinder.png"
        label="REACT - Web App"
        title="Pathfinding Visualizer"
        link="http://nikolajjsj.github.io/Pathfinder/"
      />
      <Card
        image="/assets/react/tictactoe.png"
        link="https://nikolajjsj.github.io/TicTacToe/"
        label="REACT - Web App"
        title="TicTacToe with AI"
      />
      <Card
        image="/assets/articles/bachelor.png"
        link="https://jeb.biologists.org/content/221/12/jeb179598"
        label="PEER-REVIEWED - ARTICLE"
        title="On insect cold tolerance"
      />
    </div>
  </div>
</template>

<script>
import Card from '@/components/Card.vue';
import Button from '@/components/Button.vue';

export default {
  name: 'Projects',
  components: {
    Card,
    Button,
  },
  setup() {
    const googleLink = 'https://play.google.com/store/apps/developer?id=Nikolaj+Jensen';
    const appleLink = 'https://apps.apple.com/us/developer/nikolaj-jensen/id1487634697';

    function newTab(url) {
      window.open(url, '_blank');
    }

    return {
      googleLink,
      appleLink,
      newTab,
    };
  },
};
</script>

<style scoped>
.google-ios-button-row {
  display: flex;
  align-items: center;
  justify-content: center;
}

#projects-title {
  margin: 3rem;
  text-align: center;
}

.cards {
  display: flex;
  flex-wrap: wrap;
  max-width: 1120px;
  width: 80%;
  margin: 0px auto;
}
</style>

// src/pages/projects.jsx
import React, { Component } from "react";
import ProjectCard from "../components/project-cards";
import Reddit from "../assets/reddit0.png";
import Sygeplej from "../assets/sygeplej0.png";
import Physiology from "../assets/physiology0.png";
import Pexels from "../assets/pexels0.png";

const googlePlay =
  "https://play.google.com/store/apps/developer?id=Nikolaj+Jensen";
const appleStore =
  "https://apps.apple.com/us/developer/nikolaj-jensen/id1487634697";

const style = {
  display: "flex",
  flexWrap: "wrap",
  alignItems: "center",
  flexDirection: "row",
  justifyContent: "center",
};

export default class Projects extends Component {
  render() {
    return (
      <div
        ref={this.props.reference}
        className="container-fluid text-center p-5"
      >
        <h1 className="display-4 p-5">FLUTTER PROJECTS</h1>

        <div className="row justify-content-md-center pb-5">
          <div className="col-sm">
            <a
              href={googlePlay}
              className="btn btn-dark btn-lg active m-2"
              role="button"
              target="_blank"
              rel="noopener noreferrer"
              aria-pressed="true"
            >
              Google Play
            </a>
          </div>
          <div className="col-sm">
            <a
              href={appleStore}
              className="btn btn-dark btn-lg active m-2"
              role="button"
              target="_blank"
              rel="noopener noreferrer"
              aria-pressed="true"
            >
              Apple Appstore
            </a>
          </div>
        </div>
        
        <div style={style}>
          <ProjectCard images={Reddit} title="Speed for Reddit" />
          <ProjectCard images={Pexels} title="Pexels wallpapers" />
          <ProjectCard images={Sygeplej} title="Sygeplejersken" />
          <ProjectCard images={Physiology} title="Physiology Calculator" />
        </div>
      </div>
    );
  }
}
