// src/components/Projects.vue
<template>
  <div class="projects">
    <h1 id="projects-title">PROJECTS</h1>
    <div class="google-ios-button-row">
      <Button @click="newTab(googleLink)" title="Google Play" />
      <Button @click="newTab(appleLink)" title="Apple Store" />
    </div>

    <div class="cards">
      <Card
        image="/assets/flutter/reddit.png"
        label="FLUTTER APP"
        title="Speed (Reddit Client)"
      />
      <Card
        image="/assets/flutter/sygepleje.png"
        label="FLUTTER APP"
        title="Sygeplejersken"
      />
      <Card
        image="/assets/flutter/sialia.png"
        label="FLUTTER APP"
        title="Sialia for Twitter"
      />
      <Card
        image="/assets/flutter/walls.png"
        label="FLUTTER APP"
        title="Walls"
      />
      <Card
        image="/assets/flutter/physiology.png"
        label="FLUTTER APP"
        title="Physiology"
      />
      <Card
        image="/assets/flutter/pexels.png"
        label="FLUTTER APP"
        title="Pexels Wallpapers"
      />
      <Card
        image="/assets/react/sorting.png"
        link="http://nikolajjsj.github.io/Sorting-Visualization/"
        label="REACT - Web App"
        title="Sorting Visualizer"
      />
      <Card
        image="/assets/react/pathfinder.png"
        label="REACT - Web App"
        title="Pathfinding Visualizer"
        link="http://nikolajjsj.github.io/Pathfinder/"
      />
      <Card
        image="/assets/react/tictactoe.png"
        link="https://nikolajjsj.github.io/TicTacToe/"
        label="REACT - Web App"
        title="TicTacToe with AI"
      />
      <Card
        image="/assets/articles/bachelor.png"
        link="https://jeb.biologists.org/content/221/12/jeb179598"
        label="PEER-REVIEWED - ARTICLE"
        title="On insect cold tolerance"
      />
    </div>
  </div>
</template>

<script>
import Card from '@/components/Card.vue';
import Button from '@/components/Button.vue';

export default {
  name: 'Projects',
  components: {
    Card,
    Button,
  },
  setup() {
    const googleLink = 'https://play.google.com/store/apps/developer?id=Nikolaj+Jensen';
    const appleLink = 'https://apps.apple.com/us/developer/nikolaj-jensen/id1487634697';

    function newTab(url) {
      window.open(url, '_blank');
    }

    return {
      googleLink,
      appleLink,
      newTab,
    };
  },
};
</script>

<style scoped>
.google-ios-button-row {
  display: flex;
  align-items: center;
  justify-content: center;
}

#projects-title {
  margin: 3rem;
  text-align: center;
}

.cards {
  display: flex;
  flex-wrap: wrap;
  max-width: 1120px;
  width: 80%;
  margin: 0px auto;
}
</style>

// src/components/projects.jsx
import React, { Component } from "react";
import Card from "./card";
import "../components/card.css";
import "./projects.css";

// Flutter projects
import RedditSrc from "../assets/flutter/reddit0.png";
import SygeplejSrc from "../assets/flutter/sygeplej0.png";
import PhysiologySrc from "../assets/flutter/physiology0.png";
import PexelsSrc from "../assets/flutter/pexels0.png";

//React projects
import TictactoeSrc from "../assets/react/tictactoe.png";
import PathfinderSrc from "../assets/react/pathfinder.png";
import SortingSrc from "../assets/react/sorting.png";

// articles
import bachelorArticle from "../assets/articles/bachelor.png";

export default class Projects extends Component {
  render() {
    return (
      <div className="cards" ref={this.props.scrollRef}>
        <h1>PROJECTS</h1>
        <div className="google-ios-button-row">
          <a
            href="https://play.google.com/store/apps/developer?id=Nikolaj+Jensen"
            className="btn btn-dark active m-2"
            role="button"
            target="_blank"
            rel="noopener noreferrer"
            aria-pressed="true"
          >
            Google Play
          </a>
          <a
            href="https://apps.apple.com/us/developer/nikolaj-jensen/id1487634697"
            className="btn btn-dark active m-2"
            role="button"
            target="_blank"
            rel="noopener noreferrer"
            aria-pressed="true"
          >
            Apple Appstore
          </a>
        </div>
        <div className="cards__container">
          <div className="cards__wrapper">
            <ul className="cards__items">
              <Card src={RedditSrc} label="FLUTTER APP" text="Speed for Reddit" />
              <Card src={SygeplejSrc} label="FLUTTER APP" text="Sygeplejersken" />
              <Card src={PexelsSrc} label="FLUTTER APP" text="Pexels Wallpapers" />
              <Card src={PhysiologySrc} label="FLUTTER APP" text="Physiology" />
            </ul>
            <ul className="cards__items"></ul>
            <ul className="cards__items">
              <Card
                href="http://nikolajjsj.github.io/Sorting-Visualization/"
                src={SortingSrc}
                label="REACT - Web App"
                text="Sorting Visualizer"
              />
              <Card
                src={PathfinderSrc}
                label="REACT - Web App"
                text="Pathfinding Visualizer"
                href="http://nikolajjsj.github.io/Pathfinder/"
              />
              <Card
                href="https://nikolajjsj.github.io/TicTacToe/"
                src={TictactoeSrc}
                label="REACT - Web App"
                text="TicTacToe with AI"
              />
            </ul>
            <ul className="cards__items">
              <Card
                href="https://jeb.biologists.org/content/221/12/jeb179598"
                src={bachelorArticle}
                label="PEER-REVIEWED - ARTICLE"
                text="On insect cold tolerance"
              />
            </ul>
          </div>
        </div>
      </div>
    );
  }
}
