// pages/index.vue
<template>
  <div class="home">
    <client-only>
      <Particles class="index__particles h-screen" />
    </client-only>

    <section class="home__section">
      <div class="home__section-container">
        <h1 class="home__section-container__title">Software Developer</h1>
        <p class="home__section-container__paragraph">
          Experienced Developer proficient in Dart, JavaScript, and Python. I've
          mainly worked on frontend development for both web and mobile. Mobile
          development has been with either Flutter or some native Android
          development. Whereas web development have been done with Vue and
          React.
        </p>
        <p class="home__section-container__paragraph">
          I also have a education as a biologist, where my speciality is within
          Zoophysiology. This includes laboratory work with several mammals,
          reptiles, amphibians, and insects. This work has led to a published
          peer-reviewed article, on insect cold physiology. Dataanalysis has
          been performed with Python, MatLab, and R.
        </p>
        <a href="mailto:nikolajjsj@gmail.com" class="btn"> Contact </a>
      </div>
    </section>
  </div>
</template>

<script>
import Particles from '@/components/Particles'
import Vue from 'vue'

export default Vue.extend({
  components: {
    Particles,
  },
})
</script>

<style scoped>
.index__particles {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
}

.home {
  width: 80%;
  max-width: 72rem;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  margin: auto;
  padding: 0 0 2rem;
  text-align: center;
}

.home section {
  position: relative;
}

.home__section {
  width: auto;
  display: flex;
  flex-direction: column;
  margin: 0 auto;
  padding: 0 1rem;
}

.home__section-container {
  width: 100%;
  text-align: center;
}

.home__section-container__title {
  color: var(--color-secondary);
  font-size: 2.25rem;
  line-height: 2.5rem;
  font-weight: bold;
  line-height: 1.25;
  letter-spacing: 0.025em;
}

.home__section-container__paragraph {
  /* text-sm */
  line-height: 2;
  margin: 1rem 0 1.5rem 0;
}

@media screen and (min-width: 768px) {
  .home section {
    padding-top: 4rem;
  }

  .home__section-container__paragraph {
    font-size: 1rem;
    line-height: 1.5rem;
  }

  .home__section-container__title {
    font-size: 3.75rem;
    line-height: 1;
  }
}

@media screen and (min-width: 1024px) {
  .home__section {
    flex-direction: row;
    align-items: center;
  }

  .home__section-container {
    text-align: right;
    width: 50%;
  }
}
</style>

// pages/index.tsx
import Head from 'next/head'
import styles from '../styles/Index.module.css'

import { motion } from 'framer-motion'

export default function Home() {
  return (
    <div className={styles.home}>
      <Head>
        <title>Nikolaj Jensen</title>
        <meta
          name="description"
          content="Developer portfolio of Nikolaj Jensen"
        />
      </Head>

      <section className={styles.resume}>
        <motion.h1
          className={styles.title}
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ type: 'spring', duration: 2 }}
        >
          Software
        </motion.h1>
        <motion.h1
          className={styles.title}
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ type: 'spring', delay: 0.5, duration: 2 }}
        >
          Developer
        </motion.h1>

        <p className={styles.paragraph}>
          Experienced Developer proficient in Dart, JavaScript, and Python. I've
          mainly worked on frontend development for both web and mobile. Mobile
          development has been with either Flutter or some native Android
          development. Whereas web development have been done with Vue and
          React.
        </p>

        <p className={styles.paragraph}>
          I also have a education as a biologist, where my speciality is within
          Zoophysiology. This includes laboratory work with several mammals,
          reptiles, amphibians, and insects. This work has led to a published
          peer-reviewed article, on insect cold physiology. Dataanalysis has
          been performed with Python, MatLab, and R.
        </p>

        <motion.button
          onClick={() => (location.href = 'mailto:nikolajjsj@gmail.com')}
          className="btn"
          whileHover={{ borderRadius: '2px' }}
          whileTap={{ scale: 0.9 }}
        >
          Contact
        </motion.button>
      </section>

      <motion.div
        className={styles.animation}
        style={{ background: 'var(--color-secondary)', height: '100px', width: '100px' }}
        animate={{
          scale: [1, 2, 2, 1, 1],
          rotate: [0, 0, 270, 270, 0],
          borderRadius: ['5%', '20%', '50%', '50%', '5%'],
          border: ['2px', '1px', '1px', '1px', '1px']
        }}
        transition={{ repeat: Infinity, duration: 3 }}
      ></motion.div>
    </div>
  )
}
